---

- name: Opensearch installation & configuration
  hosts: os-cluster
  become: true
  gather_facts: true
  roles:
    - { role: opensearch }

- name: Opensearch dashboards installation & configuration
  hosts: dashboards
  become: true
  gather_facts: true
  roles:
    - { role: dashboards }
