---

#- name: Disable and stop FirewallD
#  systemd:
#    name: firewalld
#    state: stopped
#    enabled: false

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: Install epel-release
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - epel-release

- name: Set timezone
  timezone:
    name: "{{ ntp_timezone }}"

- name: Force timesync with chrony
  shell: "chronyc -a makestep"

- name: Install additional packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python2-cryptography
    - setools-console
    - libsemanage-python
    - policycoreutils-python
    - pcs
    - pacemaker
    - gfs2-utils
    - lvm2-cluster
    
#- name: Set hostname
#  hostname:
#    name: "{{ ansible_hostname }}.{{ domain }}"

- name: Add my own IP address to /etc/hosts instead localhost
  replace:
    path: "/etc/hosts"
    regexp: '^127\.0\.0\.1(\s+){{ ansible_hostname }}(\s+){{ ansible_hostname }}.*'
    replace: "{{ ansible_host }} {{ ansible_hostname }}.{{ domain }} {{ ansible_hostname }}"

- name: Add pcs1 to /etc/hosts
  lineinfile:
    path: "/etc/hosts"
    state: present
    line: "192.168.10.11 pcs1.{{ domain }} pcs1"

- name: Add pcs2 to /etc/hosts
  lineinfile:
    path: "/etc/hosts"
    state: present
    line: "192.168.10.12 pcs2.{{ domain }} pcs2"

- name: Add pcs3 to /etc/hosts
  lineinfile:
    path: "/etc/hosts"
    state: present
    line: "192.168.10.13 pcs3.{{ domain }} pcs3"

- name: Set password for local hacluster user
  user:
    name: "hacluster"
    password: "{{ pcs_password | string | password_hash('sha512') }}" 
    state: present
    update_password: always
    create_home: yes
  notify: "restart pcsd"
  no_log: true

- name: Enable Pacemaker service
  systemd:
    name: pcsd.service
    enabled: true

- meta: flush_handlers
...
