---

- name: Configuring cluster (step 1)
  command: "{{ item }}"
  with_items:
    - " pcs cluster auth pcs1.{{ domain }} pcs2.{{ domain }} pcs3.{{ domain }} -u hacluster -p {{ pcs_password }}"
  no_log: true

- name: Check for replay (/opt/pcs_config_done exists)
  stat:
    path: /opt/pcs_config_done
  register: pcs_config_done

- name: Configuring cluster (step 2)
  command: "{{ item }}"
  with_items:
    - "pcs cluster setup --name {{ cluster_name }} pcs1.{{ domain }} pcs2.{{ domain }} pcs3.{{ domain }}"
  when:
    - pcs_config_done.stat.exists != True

- name: Set replay protection (/opt/pcs_config_done)
  file:
    path: /opt/pcs_config_done
    state: touch
    owner: root
    group: root
    mode: '0744'
  when:
    - pcs_config_done.stat.exists != True

- name: Configuring cluster (step 3)
  command: "{{ item }}"
  with_items:
    - "pcs cluster enable --all"
    - "pcs cluster start --all"

- name: Wait a little
  pause:
    seconds: 10

- name: Check for replay (/opt/gfs2_config_done exists)
  stat:
    path: /opt/gfs2_config_done
  register: gfs2_config_done

- name: Configure cluster resources for GFS2
  command: "{{ item }}"
  with_items:
    - pcs property set stonith-enabled=false
    - pcs property set no-quorum-policy=freeze
    - pcs resource create dlm systemd:dlm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true
    - pcs resource create clvmd ocf:heartbeat:clvm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true
    - pcs constraint order start dlm-clone then clvmd-clone
  notify: "restart pcsd"
  when:
    - gfs2_config_done.stat.exists != True

- name: Set replay protection (/opt/gfs2_config_done)
  file:
    path: /opt/gfs2_config_done
    state: touch
    owner: root
    group: root
    mode: '0744'
  when:
    - gfs2_config_done.stat.exists != True

- name: Check for replay (/opt/lvm1_config_done exists)
  stat:
    path: /opt/lvm1_config_done
  register: lvm1_config_done

- name: Create lvm GFS2 step1
  command: "{{ item }}"
  with_items:
    - lvmconf --enable-cluster
    - systemctl disable lvm2-lvmetad --now
    - pvcreate /dev/sda
    - vgcreate -Ay -cy --shared cluster_vg /dev/sda
  when:
    - lvm1_config_done.stat.exists != True

- name: Set replay protection (/opt/lvm1_config_done)
  file:
    path: /opt/lvm1_config_done
    state: touch
    owner: root
    group: root
    mode: '0744'
  when:
    - lvm1_config_done.stat.exists != True    

- name: Wait a little
  pause:
    seconds: 15
  
- name: Create lvm GFS2 step2
  command: "{{ item }}"
  with_items:
    - lvcreate -L900M -n cluster_lv cluster_vg
    - mkfs.gfs2 -O -j3 -p lock_dlm -t hacluster:hafs /dev/cluster_vg/cluster_lv

- name: Add GFS2 fs to cluster
  command: "{{ item }}"
  with_items:
    - pcs resource create clusterfs Filesystem device="/dev/cluster_vg/cluster_lv" directory="/mnt/gfs2" fstype="gfs2" "options=noatime" op monitor interval=10s on-fail=ignore clone interleave=true
    - pcs constraint order start clvmd-clone then clusterfs-clone
    - pcs constraint colocation add clusterfs-clone with clvmd-clone
...


